// all the above are possible constants that define what possible actions can be performed.

export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE";

export const DELETE_CONTACT = "DELETE_CONTACTS";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACTS_SUCCESS";
export const DELETE_CONTACT_FAILURE = "DELETE_CONTACTS_FAILURE";

export const ADD_CONTACT = "ADD_CONTACT";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT";
export const ADD_CONTACT_FAILURE = "ADD_CONTACT_FAILURE";

export const GET_CONTACT = "GET_CONTACT";
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAILURE = "GET_CONTACT_FAILURE";

export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAILURE = "UPDATE_CONTACT_FAILURE";
